/*
Generated by https://github.com/tamac-io/openapi-to-terraform-rb
*/
package ecl

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform/helper/resource"

	"github.com/nttcom/terraform-provider-ecl/ecl/testhelper/mock"
)

func TestMockedAccMLBV1RuleDataSource(t *testing.T) {
	mc := mock.NewMockController()
	defer mc.TerminateMockControllerSafety()

	postKeystone := fmt.Sprintf(fakeKeystonePostTmpl, mc.Endpoint(), OS_REGION_NAME)

	mc.Register(t, "keystone", "/v3/auth/tokens", postKeystone)
	mc.Register(t, "rules", "/v1.0/rules", testMockMLBV1RulesListNameQuery)

	mc.StartServer(t)

	resource.Test(t, resource.TestCase{
		PreCheck:  func() { testAccPreCheck(t) },
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccMLBV1RuleDataSourceQueryName,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet("data.ecl_mlb_rule_v1.rule_1", "id"),
					resource.TestCheckResourceAttr("data.ecl_mlb_rule_v1.rule_1", "name", "rule"),
					resource.TestCheckResourceAttr("data.ecl_mlb_rule_v1.rule_1", "description", "description"),
					resource.TestCheckResourceAttr("data.ecl_mlb_rule_v1.rule_1", "tags.key", "value"),
					resource.TestCheckResourceAttr("data.ecl_mlb_rule_v1.rule_1", "configuration_status", "ACTIVE"),
					resource.TestCheckResourceAttr("data.ecl_mlb_rule_v1.rule_1", "operation_status", "COMPLETE"),
					resource.TestCheckResourceAttr("data.ecl_mlb_rule_v1.rule_1", "policy_id", "fcb520e5-858d-4f9f-bc6c-7bd225fe7cf4"),
					resource.TestCheckResourceAttr("data.ecl_mlb_rule_v1.rule_1", "load_balancer_id", "67fea379-cff0-4191-9175-de7d6941a040"),
					resource.TestCheckResourceAttr("data.ecl_mlb_rule_v1.rule_1", "tenant_id", "34f5c98ef430457ba81292637d0c6fd0"),
					resource.TestCheckResourceAttr("data.ecl_mlb_rule_v1.rule_1", "priority", "1"),
					resource.TestCheckResourceAttr("data.ecl_mlb_rule_v1.rule_1", "target_group_id", "29527a3c-9e5d-48b7-868f-6442c7d21a95"),
					resource.TestCheckResourceAttr("data.ecl_mlb_rule_v1.rule_1", "conditions.0.path_patterns.0", "^/statics/"),
				),
			},
		},
	})
}

var testAccMLBV1RuleDataSourceQueryName = fmt.Sprintf(`
data "ecl_mlb_rule_v1" "rule_1" {
  name = "rule"
}
`)

var testMockMLBV1RulesListNameQuery = fmt.Sprintf(`
request:
  method: GET
  query:
    name:
      - rule
response:
  code: 200
  body: >
    {
      "rules": [
        {
          "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
          "name": "rule",
          "description": "description",
          "tags": {
            "key": "value"
          },
          "configuration_status": "ACTIVE",
          "operation_status": "COMPLETE",
          "policy_id": "fcb520e5-858d-4f9f-bc6c-7bd225fe7cf4",
          "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
          "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
          "priority": 1,
          "target_group_id": "29527a3c-9e5d-48b7-868f-6442c7d21a95",
          "conditions": {
            "path_patterns": [
              "^/statics/"
            ]
          }
        }
      ]
    }
`)
