/*
Generated by https://github.com/tamac-io/openapi-to-terraform-rb
*/
package ecl

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform/helper/resource"

	"github.com/nttcom/terraform-provider-ecl/ecl/testhelper/mock"
)

func TestMockedAccMLBV1HealthMonitorDataSource(t *testing.T) {
	mc := mock.NewMockController()
	defer mc.TerminateMockControllerSafety()

	postKeystone := fmt.Sprintf(fakeKeystonePostTmpl, mc.Endpoint(), OS_REGION_NAME)

	mc.Register(t, "keystone", "/v3/auth/tokens", postKeystone)
	mc.Register(t, "health_monitors", "/v1.0/health_monitors", testMockMLBV1HealthMonitorsListNameQuery)

	mc.StartServer(t)

	resource.Test(t, resource.TestCase{
		PreCheck:  func() { testAccPreCheck(t) },
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccMLBV1HealthMonitorDataSourceQueryName,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet("data.ecl_mlb_health_monitor_v1.health_monitor_1", "id"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "name", "health_monitor"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "description", "description"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "tags.key", "value"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "configuration_status", "ACTIVE"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "operation_status", "COMPLETE"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "load_balancer_id", "67fea379-cff0-4191-9175-de7d6941a040"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "tenant_id", "34f5c98ef430457ba81292637d0c6fd0"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "port", "80"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "protocol", "http"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "interval", "5"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "retry", "3"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "timeout", "5"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "path", "/health"),
					resource.TestCheckResourceAttr("data.ecl_mlb_health_monitor_v1.health_monitor_1", "http_status_code", "200-299"),
				),
			},
		},
	})
}

var testAccMLBV1HealthMonitorDataSourceQueryName = fmt.Sprintf(`
data "ecl_mlb_health_monitor_v1" "health_monitor_1" {
  name = "health_monitor"
}
`)

var testMockMLBV1HealthMonitorsListNameQuery = fmt.Sprintf(`
request:
  method: GET
  query:
    name:
      - health_monitor
response:
  code: 200
  body: >
    {
      "health_monitors": [
        {
          "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
          "name": "health_monitor",
          "description": "description",
          "tags": {
            "key": "value"
          },
          "configuration_status": "ACTIVE",
          "operation_status": "COMPLETE",
          "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
          "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
          "port": 80,
          "protocol": "http",
          "interval": 5,
          "retry": 3,
          "timeout": 5,
          "path": "/health",
          "http_status_code": "200-299"
        }
      ]
    }
`)
